# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35bc3b2280aa27473b36c8d600cdb7383b8cde52a26000d7d4868f15590a2b507ef4e4238c0d5c6cd985bef0f9ac34ae86b53035c4fb903cabdb0c7a45d12f95

test:
  secret_key_base: f5db3546576cbb34aaded5ebec25aa32c887161e1115572dc9a9db33321ae207f30b2887ee5197b18090c987fcc4baa738da284ae84ccbf56bfe55f8d7d79ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
